name: 24-7 Live TV Server

on:
  schedule:
    - cron: '0 */5 * * *'  # প্রতি ৫ ঘণ্টা পরপর অটোমেটিক রিস্টার্ট হবে
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install FFmpeg, Fonts & Cloudflared
        run: |
          sudo apt update
          sudo apt install ffmpeg fonts-freefont-ttf -y
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Broadcast & Public Tunnel
        run: |
          python3 -m http.server 8080 &
          cloudflared tunnel --url http://localhost:8080 &
          sleep 3
          python3 -u stream.py
          
